[package]
name = "template-py"
version = "0.1.1"
authors = ["Devdutt Shenoi <devdutt@outlook.in>"]
edition = "2018"

[lib]
name = "template_py"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.9.0"
features = ["extension-module"]
